# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
     app.avatar_uploader:
         class: Jc\ObdulioBundle\Clases\FileUploader
         arguments: ['%avatar_directory%']

     app.doctrine_brochure_listener:
        class: Jc\ObdulioBundle\Clases\AvatarUploadListener
        arguments: ['@app.avatar_uploader']
        tags:
        - { name: doctrine.event_listener, event: prePersist }
        - { name: doctrine.event_listener, event: preUpdate }

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

     login_listener:
       class: 'Jc\ObdulioBundle\EventListener\LoginListener'
       arguments: ['@security.context', '@doctrine']
       tags:
       - { name: 'kernel.event_listener', event: 'security.interactive_login' }

     jc.obduliobundle.eventlistener.logout_handler:
       class: Jc\ObdulioBundle\EventListener\LogoutHandler
       arguments: ['@security.context', '@doctrine']

