<?php

namespace Jc\ObdulioBundle\Repository;

/**
 * DestinoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DestinoRepository extends \Doctrine\ORM\EntityRepository
{
}
