<?php

namespace Jc\ObdulioBundle\Repository;

/**
 * MedidaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedidaRepository extends \Doctrine\ORM\EntityRepository
{
}
