<?php

namespace Jc\ObdulioBundle\Repository;

/**
 * PlanificacionproduccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanificacionproduccionRepository extends \Doctrine\ORM\EntityRepository
{
}
