<?php

namespace Jc\ObdulioBundle\Repository;

/**
 * PlanificaciondelecheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanificaciondelecheRepository extends \Doctrine\ORM\EntityRepository
{
}
