<?php

namespace Jc\ObdulioBundle\Repository;

/**
 * ProduccionlecheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduccionlecheRepository extends \Doctrine\ORM\EntityRepository
{
}
