<?php

namespace Jc\ObdulioBundle\Repository;

/**
 * ProduccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduccionRepository extends \Doctrine\ORM\EntityRepository
{
}
