<?php

namespace Jc\ObdulioBundle\Repository;

/**
 * SiembraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiembraRepository extends \Doctrine\ORM\EntityRepository
{
}
