<?php

namespace Jc\ObdulioBundle\Repository;

/**
 * TermoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TermoRepository extends \Doctrine\ORM\EntityRepository
{
}
