<?php

namespace Jc\ObdulioBundle\Repository;

/**
 * TipoproductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoproductoRepository extends \Doctrine\ORM\EntityRepository
{
}
