<?php

namespace Jc\ObdulioBundle\Repository;

/**
 * TipodeunidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipodeunidadRepository extends \Doctrine\ORM\EntityRepository
{
}
