<?php

namespace Jc\ObdulioBundle\Repository;

use Doctrine\ORM\EntityRepository;
//use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;

/**
 * UsuariosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuariosRepository extends EntityRepository /*implements UserLoaderInterface*/
{
    public function TodoNacional(){
        return $this->getEntityManager()
                    ->createQuery("SELECT u FROM JcObdulioBundle:Usuarios u")
                    ->getResult();
    }

    public function findUsuarioById($idUser){
        return $this->getEntityManager()
                    ->createQuery('SELECT u FROM JcObdulioBundle:Usuarios u WHERE u.id = :idUser')
                    ->setParameter('idUser', $idUser)
                    ->getResult();
    }


}

