reportes_index:
    path:     /index
    defaults: { _controller: JcObdulioBundle:Reportes:index }
reportes_operativo:
    path:     /operativo
    defaults: { _controller: JcObdulioBundle:Reportes:operativo }
reportes_operativo_totales:
    path:     /operativo/totales/{tipo}
    defaults: { _controller: JcObdulioBundle:Reportes:operativoTotales }