reporte_operativo:
    path:     /operativo
    defaults: { _controller: JcObdulioBundle:Reportes:operativo }
reporte_totales:
    path:     /totales
    defaults: { _controller: JcObdulioBundle:Reportes:totales }