reportes_index:
    path:     /
    defaults: { _controller: JcObdulioBundle:Reportes:index }
reportes_detalles:
    path:     /detalles
    defaults: { _controller: JcObdulioBundle:Reportes:detalles }
    methods:  [GET,POST]
reportes_operativo:
    path:     /operativo
    defaults: { _controller: JcObdulioBundle:Reportes:operativo }
reportes_operativo_totales:
    path:     /operativo/totales/{tipo}
    defaults: { _controller: JcObdulioBundle:Reportes:operativoTotales }