rh_usuarios_index:
    path:     /index
    defaults: { _controller: JcObdulioBundle:Usuarios:index }

rh_usuarios_add:
    path:     /agregar
    defaults: { _controller: JcObdulioBundle:Usuarios:add }
    
rh_usuarios_create:
    path:     /create
    defaults: { _controller: JcObdulioBundle:Usuarios:create}
    methods:  POST
    
rh_usuarios_edit:
    path:     /editar/{id}
    defaults: { _controller: JcObdulioBundle:Usuarios:edit}
    
rh_usuarios_update:
    path:     /update/{id}
    defaults: { _controller: JcObdulioBundle:Usuarios:update }
    methods: [POST, PUT]
    
rh_usuarios_view:
    path:     /vista/{id}
    defaults: { _controller: JcObdulioBundle:Usuarios:view }
        
rh_usuarios_cambio:
    path:     /cambio/{id}
    defaults: { _controller: JcObdulioBundle:Usuarios:cambio}
    
rh_usuarios_cambiar:
    path:     /cambiar/{id}
    defaults: { _controller: JcObdulioBundle:Usuarios:cambiar }
    methods: [POST, PUT]
    
rh_usuarios_delete:
    path:     /borrar/{id}
    defaults: { _controller: JcObdulioBundle:Usuarios:delete }
    methods: [POST, DELETE]
    
rh_usuarios_redirect_add:
    path:     /create
    defaults: 
      _controller: JcObdulioBundle:Usuarios:add
      path: /agregar
      permanent: true
      
rh_usuarios_redirect_edit:
    path:     /update/{id}
    defaults: 
      _controller: JcObdulioBundle:Usuarios:edit
      path: /editar/{id}
      permanent: true
      
rh_usuarios_redirect_cambio:
    path:     /cambiar/{id}
    defaults: 
      _controller: JcObdulioBundle:Usuarios:cambio
      path: /cambio/{id}
      permanent: true
    
